server:
  port: 8080

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/DigitalMedia
            jwk-set-uri: http://localhost:8082/realms/DigitalMedia/protocol/openid-connect/certs
        registration:
          gateway-api:
            provider: keycloak
            client-id: api-gateway
            client-secret: 4zBdFyVh83njKccG03JAo37nSUawgDd6
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8080/login/oauth2/code/keycloak'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: moviesRoute
          uri: lb://peliculas-service
          predicates:
            - Path=/movies/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: moviesService
                fallbackUri: forward:/fallback/movies
        - id: usersRoute
          uri: lb://usuarios-service
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0
            - name: CircuitBreaker
              args:
                name: usersService
                fallbackUri: forward:/fallback/users

# La ruta hacia facturacion-service no está incluída
# Según lo conversado en clase no se puede acceder al facturacion-service a través del gateway


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://eureka-server:8761/eureka/
    enabled: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
info:
  app:
    name: ${spring.application.name}
    description: Gateway Service Proyecto Integrador Materia Especialización Backend II
    version: 1.0.0

logging:
  level:
    org:
      springframework:
        security: DEBUG